### ISSUE TITLE
Problem with get the local IP in the basic.rabit example

### ISSUE THREAD

**Issue by kemaswill** [dmlc/rabit#11]
Using the current code to get local IP, e.g. host = socket.gethostbyname(socket.getfqdn()) in rabit/tracker/rabit_tracker.py will get the following ERROR on MAC
"socket.gaierror: [Errno 8] nodename nor servname provided, or not known".
host = socket.gethostbyname(socket.gethostname()) doesn't work, too.

The following changes works for me:
host = socket.gethostbyname('localhost')
I don't know if it works in all situations. Any suggestion?

**Comment by tqchen** [comment]
This means socket.gethostname does not work on your machine.  I think your change will allow you to run rabit examples locally, it may cause problem when submit job to remote machines

**Comment by bobye** [comment]
I have the same problem when I run on a new Mac. But I was able to run without modification before.

**Comment by qichaotang** [comment]
MAC host = socket.gethostbyname(socket.gethostname()) can fix it
