### ISSUE TITLE
include/rabit/serializable.h:14:10: fatal error: 'dmlc/io.h' file not found

### ISSUE THREAD

**Issue by Mrhs121** [dmlc/rabit#116]
include/rabit/serializable.h:14:10: fatal error: 'dmlc/io.h' file not found

**Comment by Mrhs121** [comment]
I have solved this problem!

I didn't set up the env of  dmlc-core before make ,so awkward! :expressionless:

**Comment by trivialfis** [comment]
Or use cmake.
