### ISSUE TITLE
Network Implementation Methods

### ISSUE THREAD

**Issue by kotbegemot** [dmlc/rabit#118]
Why is a self-written network used and not boost.asio?

**Comment by hcho3** [comment]
@kotbegemot I'm not the original author, but my guess is that Boost is a very large dependency. Rabit is meant to be a lightweight library that can be easily embedded in another application (e.g. XGBoost).

**Comment by kotbegemot** [comment]
boost.asio to pack compactly. 
[asio](https://github.com/chriskohlhoff/asio) alternative to boost.asio.

**Comment by hcho3** [comment]
I do not think at this point in time, it is wise to re-write Rabit using boost.asio. We will consider it in the future.
