### ISSUE TITLE
Rabit should import dmlc-core as a CMake target

### ISSUE THREAD

**Issue by thvasilo** [dmlc/rabit#123]
Similar to #82 , I'm testing PR #113 and in order to compile rabit I need to pull in the dmlc-core headers `dmlc-core/include/dmlc` and copy those into `rabit/include` to make the project compile.

First: Am I doing this right?
Second: If the dmlc headers are indeed a requirement to the project, should they be included (and version) in the rabit repo? Not sure what the motivation is for keeping them separate (I can imagine downstream projects that depend on both like xgboost though)

**Comment by hcho3** [comment]
Indeed, I recently found a subtle bug (#5514) because some flags from dmlc-core didn't get propagated to Rabit. Rabit should import dmlc-core as a proper CMake target.

**Comment by hcho3** [comment]
Rabit is now part of XGBoost.
