### ISSUE TITLE
Consider altering Makefile ARCH/CFLAGS Behaviour

### ISSUE THREAD

**Issue by danieldjewell** [dmlc/rabit#142]
Hello!

In troubleshooting compilation on aarch64, I noticed that the detection logic in the Makefile for the CFLAGS seems backwards to me... If I'm reading it correctly, the logic is essentially:

```
if ( ARCH is <one of these> )
    CFLAGS += -march=native
else
    CFLAGS += -msse2
```

It seems like the correct logic would be:

```
if ( ARCH is Intel )
   CFLAGS += -msse2
else
   CFLAGS += -march=native
```

https://github.com/dmlc/rabit/blob/74bf00a5ab4594f1695a8ea960394ce89f4a44d0/Makefile#L20-L25

### Rationale

* SSE is *only* present on x86(/_64). Therefore, the flag should only be used on the platforms that are known to support it. All others should default to a known working option. 
* As configured, this logic would fail to properly work on say **mips64** 

### Thoughts 

* Consider just using -march=native period:
  * In my experience, modern compilers when using -march=native do enable (most) all relevant CPU optimization flags - *including -msse2*

* In general, just a general suggestion to be really aware of portability - I'm certainly in a minority where I like to run things on x86, aarch64, mips, etc. One of the beautiful things of the *NIX ecosystem are the ideas of architecture-independent portable code. At the end of the day, IMHO, the code should build for *any* architecture for which there is a suitable build toolchain available. (I recognize that this isn't possible in *every* situation and that there are situations where one might write something in architecture-specific assembly - cryptography comes to mind - but just in general. :grin:)

**Comment by hcho3** [comment]
You are right about the use of SSE. A pull request is welcome.

**Comment by trivialfis** [comment]
I need to allocate time to bring up mpi backend.  We can't maintain a high performance mpi like library with the diversity of modern network stack.

**Comment by hcho3** [comment]
Closing, as Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).
