### ISSUE TITLE
Rabit moved into XGBoost; no issue / PR will be accepted here

### ISSUE THREAD

**Issue by hcho3** [dmlc/rabit#147]
Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).

Therefore, this repository will not accept any new issues or pull requests. Thanks for your understanding.

**Comment by trivialfis** [comment]
Well, if someone wants to use RABIT or to maintain it, I believe it's fine.  I can help reviewing PR.

**Comment by trivialfis** [comment]
But xgboost related issues are no longer accepted.
