### ISSUE TITLE
problem with submit the basic.exe to msmpi cluster

### ISSUE THREAD

**Issue by wangbin284230101** [dmlc/rabit#15]
follow your guide i compile the basic.exe ,and use rabit_demo.py to test it locally, the result is correct.
but when I try to excute as follow ,the result is wrong :

D:\cluster\clustertest\Release>mpiexec -n 4 basic.exe
@node[0] before-allreduce: a={0, 1, 2}
@node[0] after-allreduce-max: a={0, 1, 2}
@node[0] after-allreduce-sum: a={0, 1, 2}
@node[0] before-allreduce: a={0, 1, 2}
@node[0] after-allreduce-max: a={0, 1, 2}
@node[0] after-allreduce-sum: a={0, 1, 2}
@node[0] before-allreduce: a={0, 1, 2}
@node[0] after-allreduce-max: a={0, 1, 2}
@node[0] after-allreduce-sum: a={0, 1, 2}
@node[0] before-allreduce: a={0, 1, 2}
@node[0] after-allreduce-max: a={0, 1, 2}
@node[0] after-allreduce-sum: a={0, 1, 2}

by the way ,when I use the msmpi.dll and the include folder they apply to code ,and use the mpiexec command , the result is correct. 
why can't use mpiexec to submit the rabit job ?

**Comment by tqchen** [comment]
You will need to submit using rabit_mpi.py if you want to submit rabit program with MPI. Alternatively, you can link the code with rabit_mpi library which uses MPI backend instead of rabit's implementation
