### ISSUE TITLE
a problem when use mpi cluster

### ISSUE THREAD

**Issue by wangbin284230101** [dmlc/rabit#16]
I changed a little the example basic.cc , in the orignal code array a is just 3 elements , i malloc a space about 125000 double elements ,and the program stuck:
the command i use as follow:
rabit_mpi.py  -n 4 "basic.exe 125000"
code as follow:
#include <rabit.h>
using namespace rabit;
//const int N = 3;
int main(int argc, char *argv[]) {
  int *a;
  int *aa;
  int len;
  printf("start\n");
  rabit::Init(argc, argv);
  len = atoi(argv[1]);
  a = (int *)malloc(len*sizeof(int));
  aa = a;
  for (int i = 0; i < len; ++i) {
    *aa = rabit::GetRank() + i;
	aa++;
  } 
  Allreduce<op::Sum>(&a[0], len);
  printf("done\n!");
  rabit::Finalize();
  return 0;
}
is it a bug?

**Comment by wangbin284230101** [comment]
a = (int *)malloc(lensizeof(int))  above  is a display mistake when i copy to github,ignore it ,and the element type is int not double ,i am sorry.but the bug still exist.

**Comment by tqchen** [comment]
This was a win32 socket compatibility problem that I overlooked, it should be fixed now

**Comment by wangbin284230101** [comment]
thank you , I will try it. at first i think it's the allreducering function (as further the TryReduceScatterRing function )has problem  ,because when allreduce interface's element size is bigger than the reduce_ring_mincount  ,the program stuck.

**Comment by tqchen** [comment]
The socket problem was indeed revealed in TryReduceScatterRing, so your guess was reasonable:)
