### ISSUE TITLE
Can it support simple mpi send recv ?

### ISSUE THREAD

**Issue by chenghuige** [dmlc/rabit#17]
I am new to parallel programming and find rabit very elegant, easy to use.
For one simple scenario, i want to train an ensemble of trainers, each distinct node will train one and create one predictor, I want to get all the predictors in node 0 and save.How to realize this ?
Now I use rabit::Broadcast , it works but might simple send to node 0 operation be better?
Now my code looks like below

			if (rabit::GetWorldSize() > 1)
			{
				svec spredictors(_predictors.size(), "");
				for (size_t i = 0; i < _predictors.size(); i++)
				{
					if (_predictors[i] != nullptr)
					{
						spredictors[i] = serialize_util::save(_predictors[i]);
					}
					rabit::Broadcast(&spredictors[i], i % rabit::GetWorldSize()); 
					if (_predictors[i] == nullptr)
					{
						_predictors[i] = serialize_util::load<PredictorPtr>(spredictors[i]);
					}
				}
			}

**Comment by tqchen** [comment]
No, support arbitrary send/recv will make fault tolerance much harder, and it is rarely used in most of ML cases. 

Your case can be described by Allgather operation, which could be implemented(not yet exposed) in rabit. If you only need to save the model, another alternative would simply be save it into different files in parallel from each of the node.

**Comment by chenghuige** [comment]
I see, thanks!
