### ISSUE TITLE
How to make each node use multi core

### ISSUE THREAD

**Issue by chenghuige** [dmlc/rabit#20]
I use rabit_mpi.py, locally I have two computers, and my hosts file looks like
cat ~/hosts 
cp01 slots=1
cp02 slots=1
My command like
rabit_mpi.py -n 2 -H ~/hosts "./exe"

However it will use only one core in each computer,
omp_get_num_procs() --- [1]

But when submitting to big cluster in my company, each node will use full cores for openmp multithread.

How can locally do the same ?

**Comment by tqchen** [comment]
Honestly I i not know what happens in your computer, but I think this have something on the openmp side

**Comment by chenghuige** [comment]
en..  Ok, I see, thanks~
