### ISSUE TITLE
stale guide.md?

### ISSUE THREAD

**Issue by CodingCat** [dmlc/rabit#27]
it seems that the directory structure of rabit has changed a lot, e.g. rabit_demo.py does not appear anywhere while guide.md indicates that users can run the demo with this command...

**Comment by tqchen** [comment]
These are moved to dmlc-core/tracker

**Comment by CodingCat** [comment]
yeah, but rabit_demo.py does not exist anymore, and it is called `dmlc-submit`, no?

**Comment by xydrolase** [comment]
@CodingCat They are not quite the same though. `dmlc-submit` handles many more functionalities and usabilities.

I created a gist with a historical version of `rabit_demo.py`, but with the `tracker` dependency removed. So you can still run it if you have an external tracker.

**Comment by family086** [comment]
1.the old codes：https://github.com/CNevd/FM_DMLC， has rabit_demo.py；
2.new coders are removed to dmlc-core/tracker；

**Comment by hcho3** [comment]
Closing, as Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).
