### ISSUE TITLE
librabit_mpi compilation issues?

### ISSUE THREAD

**Issue by davidr** [dmlc/rabit#31]
I'm not sure if this is actually an issue or if I'm just doing something stupid. Either way, I'll happily submit a PR with documentation and/or a patch once I figure it out.

When compiling librabit_mpi (with `CXX=mpicxx MPICXX=mpicxx make mpi`) the normal librabit symbols are not exported (`RabitInit`, `RabitAllReduce`, etc.).

With the addition of `$(BPATH)/c_api.o` to the librabit_mpi line of the Makefile, the symbols are properly exported by librabit_mpi.{a,so} and using librabit_mpi as xgboost's "LIB_RABIT" allows xgboost to compile.

So, is my workaround "correct" or is the intended usage of librabit_mpi something other as a drop-in for librabit, and it's correct that librabit_mpi doesn't export the librabit symbols?

**Comment by trivialfis** [comment]
Since mpi no longer maintains a C++ wrapper now.  The MPI APIs usage in rabit will need a huge refactor.  I'm closing this issue for now.

**Comment by davidr** [comment]
After 2.5 years of me doing nothing on it, it would have been fair to close it even if you weren't right! Sorry about that. If I'd realized it was still open, I'd have closed it long ago.
