### ISSUE TITLE
are docs in guide/ folder out of date?

### ISSUE THREAD

**Issue by giantwhale** [dmlc/rabit#32]
I don't see that `../tracker/rabit_demo.py` file anywhere.  Also I am wondering what's the expected output for the first c++ demo in guide.md, coz the output i got makes no sense to me at all.

```
$ python2.7 basic.py
@node[0] before-allreduce: a=[ 0. 1. 2.]
@node[0] after-allreduce-max: a=[ 0. 1. 2.]
@node[0] after-allreduce-sum: a=[ 0. 1. 2.]
```

**Comment by xydrolase** [comment]
See #27

**Comment by trivialfis** [comment]
Duplicated #27 .
