### ISSUE TITLE
Memory leak when broadcasting in a loop

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/rabit#33]
Hi,

I am using the rabit code from https://github.com/dmlc/rabit/commit/aeb40086062876822396cbe1839d02848eeeb1bc as I am using gcc 4.4 which does not have `nullptr` and the next commit doesn't compile with the gcc 4.4 I have.

When I create a simple with a large integer array with lots of elements and broadcast it to all the nodes multiple times, I seem to be getting an error.

Here are my observations with 5 nodes/machines with 1GB memory allocated to them:
- Integer array size: 8Million , 10 loops - Works
- Integer array size: 80Million , 10 loops - Fails after 5 loops
- Integer array size: 8Million , 100 loops - Fails after 32 loops

Also, If I give 3GB memory allocated to every node/machine, with: Integer array size: 8Million , 100 loops - it fails after 64 loops

I'm using a modified code from https://github.com/dmlc/rabit/blob/a9a2a69dc1144180a43f7d2d1097264482be7817/guide/broadcast.cc where I use a int array instead of a char array, and broadcasting in a loop.

It seems to be that after I broadcast the array once, the memory is not de allocated. Do I need to write some specific code to deallocate this array which has been broadcasted ?

CC @joshyjoseph

**Comment by AbdealiJK** [comment]
It seems librabit_base.so works fine and can work on HUGE data, but librabit.a does not.
Seems like some pointers or memory not being cleared correctly

**Comment by tqchen** [comment]
Do you might post the specific code you are testing?

**Comment by AbdealiJK** [comment]
@tqchen Thanks for the reply. A quick update here: I believe that the reason for this is actually that num_global_replica can never be set to 0 - which is what I try to fix in the PR at https://github.com/dmlc/rabit/pull/38

The global replica keeps atleast 1 replica of the data I broadcast and that accumulates as I am broadcasting a large array in a loop.

**Comment by AbdealiJK** [comment]
Concluding - this was not a memory leak issue, but that the global_replica was incapable of being set to 0. The PR #38 fixes this by adding an additional condition when this is 0.
