### ISSUE TITLE
Barrier() Feature? 

### ISSUE THREAD

**Issue by bobye** [dmlc/rabit#35]
Hi, I was curious if it is possible to add a barrier function like MPI_Barrier(). Currently, it can be done by articulating a Broadcast() call.

**Comment by tqchen** [comment]
I think doing a Broadcast is equally as cheap, given the data size is small

**Comment by bobye** [comment]
Sure :_D

```cpp
#ifdef RABIT_RABIT_H_
namespace rabit {
  inline void Barrier(){ static float a = 1; rabit::Broadcast(&a, sizeof(float), 0); }
}
#endif

```

**Comment by tqchen** [comment]
contribution is actually welcomed!
