### ISSUE TITLE
Why we define a vector<uint64_t> in allreduce_base.c ?

### ISSUE THREAD

**Issue by shenpengjianke** [dmlc/rabit#40]
When I read the code in src/allreduc_base.c, I found that you define a `vector<uint64_t>` buffer. 

I'm a little confused. 

Why not define a  `vector<char>` buffer?

What's the benefit?

Could you explain more specific  and name an example?

              // recv buffer ot get data from child

		// aligned with 64 bits, will be all to perform 64 bits operations freely

		std::vector<uint64_t> buffer_;`

**Comment by tqchen** [comment]
mainly for alignment purposes. You cannot simply cast a char pointer to uint64_t(because potential of alignment issues), but you can do it the other way around
