### ISSUE TITLE
What's the difference between AllreduceRing and AllreduceTree?

### ISSUE THREAD

**Issue by shenpengjianke** [dmlc/rabit#42]
I noticed that when data is big enough, the code seems to choose `TryAllreduceRing()` function rather than `TryAllreduceTree()` function.
Is the `TryAllreduceRing()`'s performance better than `TryAllreduceTree()`?
If so, in what's way? 
I guess the communication cost is the key.
I googled the question, but can't get the suitable answer.
Looking for your reply.

**Comment by thvasilo** [comment]
They are different communication algorithms, each fits a different problem.

If you want to dig a bit deeper look into this article on [MXNet](https://cwiki.apache.org/confluence/display/MXNET/Single+machine+All+Reduce+Topology-aware+Communication) or take a look around the web for [collective communication primitives](http://hunch.net/~mltf/parallel_learning.pdf), most parallel programming course should cover these.
