### ISSUE TITLE
can rabit support multi-machine parallel without MPI

### ISSUE THREAD

**Issue by caohaox** [dmlc/rabit#47]
in demo
../tracker/rabit_demo.py -n 2 basic.rabit
is multi-process in single machine；

if i want to run the program on multi-machine without MPI version；how to use？

**Comment by MaJun-cn** [comment]
hello sir ，Do you know how to implement distributed rabit?

**Comment by hcho3** [comment]
Closing, as Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).
