### ISSUE TITLE
Purpose of -msse2 flag used while compiling the rabit source code ?

### ISSUE THREAD

**Issue by snehlatamohite** [dmlc/rabit#48]
Hi,

Its been observed that -msse2 flag is used while compiling the code. We have not found any SSE/Intel specific code available in rabit source code. Can we remove the flag since it is no longer needed? It will help to compile code different architectures (apart from x86) without changes in Makefile.

I think this can be solved like what has been done in MXNet: https://github.com/dmlc/mxnet/blob/master/make/config.mk#L119-L124

Thanks,
Snehlata Mohite.

**Comment by tqchen** [comment]
I think this can be safely removed for now
