### ISSUE TITLE
[00:21:03] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [00:21:03] src/./common/config.h:179: cannot open file xgtree.conf terminate called after throwing an instance of 'dmlc::Error'

### ISSUE THREAD

**Issue by wbbhwbbwtc** [dmlc/rabit#61]
[00:21:03] rabit/include/rabit/./internal/../../dmlc/././logging.h:245: [00:21:03] src/./common/config.h:179: cannot open file xgtree.conf
terminate called after throwing an instance of 'dmlc::Error'

I got this when trying to run xgboost in a remote machine.

**Comment by hcho3** [comment]
It looks like the file `xgtree.conf` is not being deployed properly. Are you using `dmlc-submit`?

**Comment by trivialfis** [comment]
Closing due to lack of response.
