### ISSUE TITLE
Fault tolerance not work: Allreduce Recovered data size do not match the specification of function call

### ISSUE THREAD

**Issue by chinwy** [dmlc/rabit#63]
I ran xgboost on yarn and test if fault tolerance could work. I started 4 workers. When xgboost started to update model, I killed one worker(called worker0). Yarn started a worker named worker0_1 instead. But the worker failed finally due to this error:  Allreduce Recovered data size do not match the specification of function call.
    The responding code is,
allreduce_robust.cc(line 817)
  if (role == kRequestData || role == kHaveData) {
    utils::Check(data_size == size,
                 "Allreduce Recovered data size do not match the specification of function call.\n"\
                 "Please check if calling sequence of recovered program is the " \
                 "same the original one in current VersionNumber");
  }

I printed some details then. data_size is 800 and size is 8. But I don't know the reason.

**Comment by CodingCat** [comment]
@chenqin FYI....long way to go

**Comment by chenqin** [comment]
please try this https://github.com/chenqin/xgboost/commit/bca9103966dee3b5c85390d8d39d3464aacc74d5

**Comment by hcho3** [comment]
Closing, as Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).
