### ISSUE TITLE
How to run rabit on cluster?

### ISSUE THREAD

**Issue by MaJun-cn** [dmlc/rabit#76]
please，I want to know more details about using the rabit to implement program communication  in a distributed cluster.

**Comment by MaJun-cn** [comment]
please, I want to know how to use it.

**Comment by chenqin** [comment]
@MaJun-cn Can you elaborate what do communication protocol you are looking for? rabit implemented MPI all-reduce and broadcast interface with plain socket in C++. Tracker by default using python to keep track of all participants.
