### ISSUE TITLE
dmlc-submit does not accept ssh cluster type

### ISSUE THREAD

**Issue by tanmaykm** [dmlc/rabit#93]
`dmlc-submit` does not accept ssh cluster type.

I see that [`ssh.py`](https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_tracker/ssh.py) exists, but it is not included in [`submit.py`](https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_tracker/submit.py). I was able to run a small test with ssh cluster type after changing `sybmit.py` to include `ssh.py` and accepting it as an option.

Is there any specific reason why it was left out?

**Comment by tanmaykm** [comment]
This was discussed earlier here https://github.com/dmlc/dmlc-core/issues/137. As I understand it was closed then because `ssh.py` didn't exist in this repo. It was subsequently added with https://github.com/dmlc/dmlc-core/pull/125. But corresponding change to `submit.py` was not made.

**Comment by hcho3** [comment]
Closing, as Rabit have been moved into [dmlc/xgboost](https://github.com/dmlc/xgboost). See discussion in [dmlc/xgboost#5995](https://github.com/dmlc/xgboost/issues/5995).
